# Module for term library, the terminal oriented library for habitat
# Nigel Stuckey, July 2002
#
# Copyright System Garden Ltd 1996-2002. All rights reserved.

SRC += 			\
trm/cmdln.c		\
trm/cursvu.c

INC += 			\
trm/cmdln.h		\
trm/cursvu.h

SOLIB += trm/libtrm.so

# Library product
trm/libtrm.so: $(patsubst %.c, %.o, $(filter trm/%.c, $(SRC))) \
			-lreadline -lcurses
	$(LINK.o) -shared $^ -o $@ #pg -a

