/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_baseWindow (void);
GtkWidget* create_about_dialog (void);
GtkWidget* create_file_open_select (void);
GtkWidget* create_curve_colour (void);
GtkWidget* create_import_window (void);
GtkWidget* create_export_window (void);
GtkWidget* create_file_close_dialog (void);
GtkWidget* create_file_import_select (void);
GtkWidget* create_file_export_select (void);
GtkWidget* create_data_app_window (void);
GtkWidget* create_data_email_window (void);
GtkWidget* create_data_save_window (void);
GtkWidget* create_file_data_save_select (void);
GtkWidget* create_open_host_window (void);
GtkWidget* create_open_route_window (void);
GtkWidget* create_start_clockwork_window (void);
GtkWidget* create_stop_clockwork_window (void);
GtkWidget* create_alert_window (void);
GtkWidget* create_log_popup_window (void);
GtkWidget* create_choice_popup_menu (void);
GtkWidget* create_choice_prop_window (void);
GtkWidget* create_repos_prop_window (void);
